# Generated by Django 3.2.7 on 2021-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_productdetail_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
